/**********************************************************************
 * Extern for geohash
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var geohash = {
  "ENCODE_AUTO": {},
  "bboxes": function () {},
  "bboxes_int": function () {},
  "decode": function () {},
  "decode_bbox": function () {},
  "decode_bbox_int": function () {},
  "decode_bbox_uint64": function () {},
  "decode_int": function () {},
  "decode_uint64": function () {},
  "encode": function () {},
  "encode_int": function () {},
  "encode_uint64": function () {},
  "neighbor": function () {},
  "neighbor_int": function () {},
  "neighbors": function () {},
  "neighbors_int": function () {}
};
/**********************************************************************
 * End Generated Extern for geohash
/**********************************************************************/
