/**********************************************************************
 * Extern for h3
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var h3 = {
  "UNITS": {
    "km": {},
    "km2": {},
    "m": {},
    "m2": {}
  },
  "compact": function () {},
  "degsToRads": function () {},
  "edgeLength": function () {},
  "experimentalH3ToLocalIj": function () {},
  "experimentalLocalIjToH3": function () {},
  "geoToH3": function () {},
  "getDestinationH3IndexFromUnidirectionalEdge": function () {},
  "getH3IndexesFromUnidirectionalEdge": function () {},
  "getH3UnidirectionalEdge": function () {},
  "getH3UnidirectionalEdgeBoundary": function () {},
  "getH3UnidirectionalEdgesFromHexagon": function () {},
  "getOriginH3IndexFromUnidirectionalEdge": function () {},
  "getPentagonIndexes": function () {},
  "getRes0Indexes": function () {},
  "h3Distance": function () {},
  "h3GetBaseCell": function () {},
  "h3GetFaces": function () {},
  "h3GetResolution": function () {},
  "h3IndexesAreNeighbors": function () {},
  "h3IsPentagon": function () {},
  "h3IsResClassIII": function () {},
  "h3IsValid": function () {},
  "h3Line": function () {},
  "h3SetToMultiPolygon": function () {},
  "h3ToCenterChild": function () {},
  "h3ToChildren": function () {},
  "h3ToGeo": function () {},
  "h3ToGeoBoundary": function () {},
  "h3ToParent": function () {},
  "h3UnidirectionalEdgeIsValid": function () {},
  "hexArea": function () {},
  "hexRing": function () {},
  "kRing": function () {},
  "kRingDistances": function () {},
  "numHexagons": function () {},
  "polyfill": function () {},
  "radsToDegs": function () {},
  "uncompact": function () {}
};
/**********************************************************************
 * End Generated Extern for h3
/**********************************************************************/
